FROM python:3.10
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir streamlit requests
COPY . .
CMD ["streamlit", "run", "frontend/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"] 